### ISSUE TITLE
Lab Report 2 Feedback

### ISSUE THREAD

**Issue by joy002** [shreyagupta112/cse15l-lab-reports#2]
**Bug/Input 1**
- [x] Commit screenshot for bug/input 1
   - Need a screenshot of commit.
- [x] Link to test file for bug/input 1
   - the link page linked me to 404
- [x] Symptom shown as command + output for bug/input 1
- [x] Description of relationship between bug, symptom, and input for bug/input 1

**Bug/Input 2**
- [x] Commit screenshot for bug/input 2
   - Need a screenshot of commit.
- [x] Link to test file for bug/input 2
   - Need a separate link to test file from your bug 1
- [x] Symptom shown as command + output for bug/input 2
   - Please separate this part from bug/input 1.
- [x] Description of relationship between bug, symptom, and input for bug/input 2
   - Please separate this part from bug/input 1.

**Bug/Input 3**
- [x] Commit screenshot for bug/input 3
   - Need a screenshot of commit.
- [x] Link to test file for bug/input 3
   - Need a separate link to test file from your bug 1
- [x] Symptom shown as command + output for bug/input 3
   - Please separate this part from bug/input 1.
- [x] Description of relationship between bug, symptom, and input for bug/input 3
   - Please separate this part from bug/input 1.

Additional comments from your grader:
Please separate the bugs and fixes into 3 cases.

Feel free to comment below if you have any questions about the rubric/feedback.

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by joy002** [comment]
You need the command(java ...) for your in bug1 and bug2. (Look at bug3 if you don't understand what I mean). Feel free to ask any questions

**Comment by shreyagupta112** [comment]
Hello,
I just added that commands.  Thank you for your help!
